### ISSUE TITLE
Req: Change ifs to enable component extensability

### ISSUE THREAD

**Issue by danielgek** [csakaszamok/csak-tree#3]
Hi, @csakaszamok, i would like to change a few if's that give some trouble while extending a new element to your's

this happens on a few lines, for example [csak-tree.html#L158](https://github.com/csakaszamok/csak-tree/blob/master/csak-tree.html#L158) you have `if (item instanceof CsakTreeItem) {` if i extend my component to CsakTreeItem(ex: MyTreeItem) `instanceof` don't work

The thing is i changed the if to `if(item.updateStyles)` but that bad because it's basically all the polymr components, what do you think ??

**Comment by danielgek** [comment]
Never mind, another thing was causing the problem

**Comment by csakaszamok** [comment]
nope
